packages:
  - packages/*
  - examples/*
  - apps/*
  - bench/beir

allowBuilds:
  core-js: true
  esbuild: true
  sharp: true

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9

overrides:
  serialize-javascript: 7.1.0
  uuid: 11.1.1
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
