import { readFile } from "node:fs/promises";
import path from "node:path";
import { runIntegrationBuild, type GeneratedHTMLOptions, type SearchConfig } from "@seekite/build";
import type { Plugin, ResolvedConfig } from "vite";

export interface SeekiteViteOptions {
  config?: string | SearchConfig;
  /** `vite` generates the index; `external` serves an index generated by CI. */
  indexing?: "vite" | "external";
  /** Directory below Vite's public/out directory. */
  assetsDir?: string;
  /** Rendered-HTML selectors used by framework wrappers such as VitePress. */
  html?: Omit<GeneratedHTMLOptions, "directory">;
}

function normalizedAssetsDir(value: string | undefined): string {
  const assetsDir = (value ?? "search").replace(/^\/+|\/+$/g, "");
  if (!assetsDir || assetsDir.split(/[\\/]/).includes("..")) {
    throw new Error(
      "Seekite assetsDir must be a relative directory inside Vite's public/out directory",
    );
  }
  return assetsDir;
}

export function seekite(options: SeekiteViteOptions = {}): Plugin {
  let viteConfig: ResolvedConfig;
  const assetsDir = normalizedAssetsDir(options.assetsDir);
  const assetPrefix = `/${assetsDir}/`;

  return {
    name: "seekite",
    enforce: "post",
    configResolved(config) {
      viteConfig = config;
    },
    async buildStart() {
      if (options.indexing !== "external" || viteConfig.command !== "build") return;
      const manifestPath = path.join(viteConfig.publicDir, assetsDir, "manifest.json");
      try {
        await readFile(manifestPath);
      } catch {
        this.error(
          `Seekite external indexing expected ${manifestPath}. Run \`seekite build --output ${path.join(viteConfig.publicDir, assetsDir)}\` in CI before Vite.`,
        );
      }
    },
    async configureServer(server) {
      if (options.indexing === "external") return;
      const outputDirectory = path.join(viteConfig.publicDir, assetsDir);
      server.middlewares.use((request, response, next) => {
        void (async () => {
          try {
            const pathname = decodeURIComponent(
              new URL(request.url ?? "/", "http://seekite.local").pathname,
            );
            if (!pathname.startsWith(assetPrefix)) return next();
            const assetPath = path.resolve(outputDirectory, pathname.slice(assetPrefix.length));
            if (!assetPath.startsWith(`${path.resolve(outputDirectory)}${path.sep}`)) return next();
            const contents = await readFile(assetPath);
            response.statusCode = 200;
            response.setHeader(
              "Content-Type",
              assetPath.endsWith(".json")
                ? "application/json; charset=utf-8"
                : "application/octet-stream",
            );
            response.setHeader("Cache-Control", "no-store");
            response.end(contents);
          } catch {
            next();
          }
        })();
      });

      let timer: ReturnType<typeof setTimeout> | undefined;
      let building = false;
      let pending = false;
      const rebuild = async (): Promise<void> => {
        if (building) {
          pending = true;
          return;
        }
        building = true;
        try {
          await runIntegrationBuild({
            root: viteConfig.root,
            htmlDir: ".",
            outDir: outputDirectory,
            config: options.config,
            html: options.html,
          });
        } catch (error) {
          server.config.logger.error(
            error instanceof Error ? (error.stack ?? error.message) : String(error),
          );
        } finally {
          building = false;
          if (pending) {
            pending = false;
            void rebuild();
          }
        }
      };
      const schedule = (changedPath: string) => {
        if (changedPath.startsWith(outputDirectory)) return;
        if (timer) clearTimeout(timer);
        timer = setTimeout(() => void rebuild(), 75);
      };
      await rebuild();
      server.watcher.on("add", schedule);
      server.watcher.on("change", schedule);
      server.watcher.on("unlink", schedule);
    },
    async closeBundle() {
      if (viteConfig.command !== "build" || options.indexing === "external") return;
      const htmlDirectory = path.resolve(viteConfig.root, viteConfig.build.outDir);
      await runIntegrationBuild({
        root: viteConfig.root,
        htmlDir: htmlDirectory,
        outDir: path.join(htmlDirectory, assetsDir),
        config: options.config,
        html: options.html,
      });
    },
  };
}
