/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A loaded embedding model.
 *
 * Construction parses and verifies the packed `.bin` (sha256 trailer, header,
 * full layout walk) and pre-decodes the hot weight sections, so it costs
 * ~100 ms and a few MB; hold onto the instance rather than rebuilding it.
 * Once built it is immutable, which is why `embed` takes `&self` and why
 * batching can fan out across threads.
 */
export declare class Engine {
  /**
   * Build an engine from packed model bytes (the contents of a
   * `models/<name>-int4.bin` asset).
   *
   * Errors — rather than panics — on any malformed input: bad magic, wrong
   * wire-format version, an embedding format this build was not compiled for,
   * a failed sha256, or a body length that disagrees with the header's layout.
   */
  constructor(modelBytes: Buffer);
  /** Output vector width (384 for both shipped models). */
  dimensions(): number;
  /** Maximum token count; longer inputs are truncated by the tokenizer. */
  maxSeqLen(): number;
  /**
   * Human-readable header summary. Matches the wasm build's `config_summary()`
   * byte for byte, which makes it a quick "am I running the same weights?"
   * check when parity tests disagree.
   */
  configSummary(): string;
  /**
   * Token ids for `text`, padded to `max_seq_len`. Diagnostic only — parity
   * failures are almost always tokenizer drift, and this localises them.
   */
  tokenize(text: string): Array<number>;
  /**
   * Embed one text into an L2-normalised vector.
   *
   * Synchronous on purpose: a single short text is ~1 ms, well under the
   * threshold where handing work to the thread pool pays for itself. Use
   * [`Engine::embed_batch`] for anything corpus-sized.
   */
  embed(text: string): Float32Array;
  /**
   * Embed many texts on a worker thread pool, resolving to one
   * `Float32Array` per input in input order.
   *
   * Parallelism is **across** texts only, never within a text: each forward
   * pass is an independent, side-effect-free function of `(model, text)`, so
   * every element is bit-identical to what a sequential [`Engine::embed`]
   * would have produced. Thread count only changes timing, never output.
   *
   * `concurrency` defaults to rayon's global pool (one thread per core). A
   * smaller value is useful when the caller is already parallel — `seekite
   * build` embedding several corpora at once, say — and wants to cap total
   * CPU. Passing a value builds a dedicated pool for the call, so prefer
   * large batches over many small ones when you set it.
   */
  embedBatch(
    texts: Array<string>,
    concurrency?: number | undefined | null,
  ): Promise<Float32Array[]>;
}

/**
 * XXH64 of `input`, returned as a BigInt (the full unsigned 64-bit value —
 * a JS `number` would silently lose the low bits).
 *
 * Exposed here rather than in JS because spec 06 hashes every source file on
 * every build; doing it in the addon keeps the cache-key cost off the main
 * thread's critical path and avoids a second hashing implementation.
 */
export declare function xxhash64(input: Buffer, seed?: bigint | undefined | null): bigint;
