import { createSearch, type QueryOptions, type SearchResult } from "@seekite/core";
import {
  createSearchController,
  type SearchController,
  type SearchUIClient,
  type SearchUIState,
} from "@seekite/search-ui";
import {
  defineComponent,
  h,
  onBeforeUnmount,
  shallowRef,
  type Component,
  type PropType,
  type VNodeChild,
} from "vue";

export interface SeekiteSearchBoxProps {
  /** Existing client/controller escape hatches for custom embeddings or shared state. */
  client?: SearchUIClient;
  controller?: SearchController;
  /** Build-relative asset key generated by the VitePress plugin. */
  assetKey?: string;
  corpora?: string[];
  facets?: string[];
  queryOptions?: QueryOptions;
  label?: string;
  placeholder?: string;
  navigate?: (url: string) => void;
}

export interface CreateVitePressSearchControllerOptions {
  client?: SearchUIClient;
  assetKey?: string;
  corpora?: string[];
  facets?: string[];
  queryOptions?: QueryOptions;
}

/** Create the headless controller used by the Vue component. */
export function createVitePressSearchController(
  options: CreateVitePressSearchControllerOptions = {},
): SearchController {
  const queryOptions: QueryOptions = {
    ...options.queryOptions,
    ...(options.corpora?.length ? { corpora: [...options.corpora] } : {}),
    ...(options.facets?.length ? { facets: [...options.facets] } : {}),
  };
  return createSearchController({
    client: options.client ?? createSearch({ key: options.assetKey ?? "search" }),
    queryOptions,
    recentStorageKey: "seekite:vitepress:recent",
  });
}

function moveToResult(controller: SearchController, state: SearchUIState, target: number): void {
  const count = state.response?.results.length ?? 0;
  if (count === 0 || target < 0 || target >= count || state.selectedIndex === target) return;
  let selected = state.selectedIndex;
  if (selected < 0) {
    controller.moveSelection(1);
    selected = 0;
  }
  while (selected !== target) {
    controller.moveSelection(1);
    selected = (selected + 1) % count;
  }
}

function snippetNodes(controller: SearchController, result: SearchResult): VNodeChild[] {
  const snippet = controller.snippetFor(result);
  const nodes: VNodeChild[] = [];
  let cursor = 0;
  for (const [start, end] of snippet.ranges) {
    if (start > cursor) nodes.push(snippet.text.slice(cursor, start));
    nodes.push(h("mark", snippet.text.slice(start, end)));
    cursor = end;
  }
  if (cursor < snippet.text.length) nodes.push(snippet.text.slice(cursor));
  return nodes;
}

/**
 * VitePress-native Vue search component backed by `@seekite/search-ui`.
 * It is SSR-safe and renders a WAI-ARIA combobox/listbox without a Vue package fork.
 */
export const SeekiteSearchBox = defineComponent({
  name: "SeekiteSearchBox",
  props: {
    client: Object as PropType<SearchUIClient>,
    controller: Object as PropType<SearchController>,
    assetKey: { type: String, default: "search" },
    corpora: { type: Array as PropType<string[]>, default: () => [] },
    facets: { type: Array as PropType<string[]>, default: () => [] },
    queryOptions: Object as PropType<QueryOptions>,
    label: { type: String, default: "Search documentation" },
    placeholder: { type: String, default: "Search docs…" },
    navigate: Function,
  },
  setup(props) {
    const ownsController = !props.controller;
    const controller =
      props.controller ??
      createVitePressSearchController({
        client: props.client,
        assetKey: props.assetKey,
        corpora: props.corpora,
        facets: props.facets,
        queryOptions: props.queryOptions,
      });
    const state = shallowRef(controller.getState());
    const unsubscribe = controller.subscribe(() => {
      state.value = controller.getState();
    });
    onBeforeUnmount(() => {
      unsubscribe();
      if (ownsController) controller.destroy();
    });

    const navigate = (result: SearchResult): void => {
      controller.close();
      if (props.navigate) props.navigate(result.url);
      else globalThis.location?.assign(result.url);
    };
    const select = (index: number): void => {
      moveToResult(controller, state.value, index);
      const result = controller.selectResult() ?? state.value.response?.results[index];
      if (result) navigate(result);
    };
    const onInput = (event: Event): void => {
      if (event.currentTarget instanceof HTMLInputElement) {
        controller.setQuery(event.currentTarget.value);
      }
    };
    const onKeydown = (event: KeyboardEvent): void => {
      if (event.isComposing) return;
      if (event.key === "ArrowDown" || event.key === "ArrowUp") {
        event.preventDefault();
        controller.moveSelection(event.key === "ArrowDown" ? 1 : -1);
        return;
      }
      if (event.key === "Escape") {
        event.preventDefault();
        controller.escape();
        return;
      }
      if (event.key !== "Enter") return;
      const result = controller.selectResult();
      if (result) {
        event.preventDefault();
        navigate(result);
      }
    };

    return () => {
      const snapshot = state.value;
      const results = snapshot.response?.results ?? [];
      const listboxId = "seekite-vitepress-results";
      return h("div", { class: "seekite-vitepress-search", "data-status": snapshot.status }, [
        h("input", {
          class: "seekite-vitepress-input",
          type: "search",
          role: "combobox",
          value: snapshot.query,
          placeholder: props.placeholder,
          "aria-label": props.label,
          "aria-autocomplete": "list",
          "aria-expanded": snapshot.open,
          "aria-controls": snapshot.open ? listboxId : undefined,
          "aria-activedescendant":
            snapshot.open && snapshot.selectedIndex >= 0
              ? `${listboxId}-${snapshot.selectedIndex}`
              : undefined,
          onInput,
          onFocus: () => {
            controller.open();
            void controller.prefetch();
          },
          onKeydown,
        }),
        snapshot.open
          ? h("div", { class: "seekite-vitepress-panel" }, [
              snapshot.status === "error"
                ? h(
                    "p",
                    { class: "seekite-vitepress-error", role: "alert" },
                    snapshot.error?.message ?? "Search failed.",
                  )
                : undefined,
              snapshot.query && snapshot.status === "ready" && results.length === 0
                ? h("p", { class: "seekite-vitepress-empty" }, "No matching pages.")
                : undefined,
              h(
                "ul",
                {
                  id: listboxId,
                  class: "seekite-vitepress-results",
                  role: "listbox",
                  "aria-label": props.label,
                  "aria-busy": snapshot.status === "loading",
                },
                results.map((result, index) =>
                  h(
                    "li",
                    {
                      id: `${listboxId}-${index}`,
                      key: `${result.corpus}:${result.id}`,
                      class: [
                        "seekite-vitepress-result",
                        snapshot.selectedIndex === index && "is-selected",
                      ],
                      role: "option",
                      "aria-selected": snapshot.selectedIndex === index,
                      onPointermove: () => moveToResult(controller, state.value, index),
                      onMousedown: (event: MouseEvent) => event.preventDefault(),
                      onClick: () => select(index),
                    },
                    [
                      h("strong", { class: "seekite-vitepress-title" }, result.title),
                      result.heading
                        ? h("span", { class: "seekite-vitepress-heading" }, result.heading)
                        : undefined,
                      h(
                        "span",
                        { class: "seekite-vitepress-snippet" },
                        snippetNodes(controller, result),
                      ),
                    ],
                  ),
                ),
              ),
              h(
                "span",
                {
                  class: "seekite-vitepress-status",
                  role: "status",
                  "aria-live": "polite",
                },
                snapshot.status === "loading"
                  ? "Loading results"
                  : snapshot.status === "ready"
                    ? `${snapshot.response?.total ?? 0} results`
                    : "",
              ),
            ])
          : undefined,
      ]);
    };
  },
});

export interface SeekiteVitePressThemeOptions extends SeekiteSearchBoxProps {
  /** Slot used by VitePress's default layout. */
  slot?: "nav-bar-content-before" | "nav-bar-content-after";
}

export interface VitePressThemeLike {
  Layout?: Component;
  [key: string]: unknown;
}

/** Insert `SeekiteSearchBox` into VitePress's default-theme navigation. */
export function withSeekiteSearch<Theme extends VitePressThemeLike>(
  theme: Theme,
  options: SeekiteVitePressThemeOptions = {},
): Theme & { Layout: Component } {
  const Layout = theme.Layout;
  if (!Layout) throw new Error("withSeekiteSearch requires a VitePress theme with a Layout");
  const { slot = "nav-bar-content-before", ...searchProps } = options;
  const WrappedLayout = defineComponent({
    name: "SeekiteVitePressLayout",
    setup(_props, { slots }) {
      return () => {
        const existing = slots[slot];
        return h(Layout, undefined, {
          ...slots,
          [slot]: () => [h(SeekiteSearchBox, searchProps), existing?.()],
        });
      };
    },
  });
  return { ...theme, Layout: WrappedLayout };
}

export interface HeadlessSearchResult {
  url: string;
}

export interface HeadlessSearchController<State, Result extends HeadlessSearchResult> {
  getState(): State;
  subscribe(listener: () => void): () => void;
  setQuery(value: string): void;
  moveSelection(delta: 1 | -1): void;
  selectResult(): Result | undefined;
  prefetch(): Promise<void>;
  open(): void;
  escape(): "cleared" | "closed";
}

export interface SeekiteSearchBoxOptions<State, Result extends HeadlessSearchResult> {
  controller: HeadlessSearchController<State, Result>;
  input: HTMLInputElement;
  render(state: State): void;
  navigate?(url: string): void;
}

export interface SeekiteSearchBoxBinding {
  destroy(): void;
}

/** Low-level binding retained for fully custom VitePress theme renderers. */
export function bindSeekiteSearchBox<State, Result extends HeadlessSearchResult>(
  options: SeekiteSearchBoxOptions<State, Result>,
): SeekiteSearchBoxBinding {
  const { controller, input } = options;
  const render = () => options.render(controller.getState());
  const unsubscribe = controller.subscribe(render);
  const onInput = () => controller.setQuery(input.value);
  const onFocus = () => {
    controller.open();
    void controller.prefetch();
  };
  const onKeydown = (event: KeyboardEvent) => {
    if (event.key === "ArrowDown" || event.key === "ArrowUp") {
      event.preventDefault();
      controller.moveSelection(event.key === "ArrowDown" ? 1 : -1);
      return;
    }
    if (event.key === "Escape") {
      event.preventDefault();
      if (controller.escape() === "cleared") input.value = "";
      return;
    }
    if (event.key !== "Enter") return;
    const result = controller.selectResult();
    if (!result) return;
    event.preventDefault();
    if (options.navigate) options.navigate(result.url);
    else globalThis.location?.assign(result.url);
  };

  input.addEventListener("input", onInput);
  input.addEventListener("focus", onFocus);
  input.addEventListener("keydown", onKeydown);
  render();

  return {
    destroy() {
      unsubscribe();
      input.removeEventListener("input", onInput);
      input.removeEventListener("focus", onFocus);
      input.removeEventListener("keydown", onKeydown);
    },
  };
}
