import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

/** Which packed model to load. Both are 384-dimensional; `base` is wider and slower. */
export type NativeModelName = "mini" | "base";

export interface NativeEngineOptions {
  /** Defaults to `"mini"`, matching `@seekite/embeddings-ternlight`'s default export. */
  model?: NativeModelName;
}

export interface NativeEngine {
  /** Output vector width. 384 for both shipped models. */
  readonly dimensions: number;
  /** Embed one text into an L2-normalised `Float32Array`. */
  embed(text: string): Float32Array;
  /**
   * Embed many texts off the main thread, one vector per input, in input order.
   *
   * Each result is bit-identical to the corresponding `embed()` call —
   * parallelism is across texts, never inside one.
   */
  embedBatch(texts: string[], concurrency?: number): Promise<Float32Array[]>;
  /** Header summary of the loaded weights; identical to the wasm build's `config_summary()`. */
  configSummary(): string;
}

// ── Native binding ──────────────────────────────────────────────────────────
//
// `binding.cjs` is generated by napi-rs and *throws* when no prebuild matches
// the host platform. That is the normal, expected path on any platform outside
// the published matrix, so the load is wrapped and the failure recorded rather
// than propagated: callers ask `isSupported()` and fall back to wasm.

interface NativeBinding {
  Engine: new (modelBytes: Buffer) => {
    dimensions(): number;
    maxSeqLen(): number;
    configSummary(): string;
    tokenize(text: string): number[];
    embed(text: string): Float32Array;
    embedBatch(texts: string[], concurrency?: number | null): Promise<Float32Array[]>;
  };
  xxhash64(input: Buffer, seed?: bigint | null): bigint;
}

const require = createRequire(import.meta.url);

let binding: NativeBinding | undefined;
let bindingError: Error | undefined;
let loadAttempted = false;

/**
 * Escape hatch: set `SEEKITE_DISABLE_NATIVE=1` to force every consumer down the
 * wasm path even when a prebuild is installed.
 *
 * Two things need this. Users need a way to rule the addon out when triaging a
 * bug without uninstalling packages, and CI needs to prove the wasm fallback
 * still works on a machine where the native binary loads fine. Read per call
 * rather than at import so a test can flip it and see the effect.
 */
function nativeDisabled(): boolean {
  const flag = process.env["SEEKITE_DISABLE_NATIVE"];
  return flag !== undefined && flag !== "" && flag !== "0" && flag !== "false";
}

/** Load the addon at most once; `undefined` means "use wasm instead". */
function loadBinding(): NativeBinding | undefined {
  if (nativeDisabled()) return undefined;
  if (!loadAttempted) {
    loadAttempted = true;
    try {
      binding = require("../binding.cjs") as NativeBinding;
    } catch (error) {
      bindingError = error instanceof Error ? error : new Error(String(error));
    }
  }
  return binding;
}

/**
 * Whether a native prebuild is available and enabled on this host.
 *
 * `false` is not an error condition — it is the signal for callers to use the
 * wasm engine. Install is deliberately compile-free, so platforms outside the
 * published matrix simply do not get a binary.
 */
export function isSupported(): boolean {
  return loadBinding() !== undefined;
}

/**
 * Why the native binding failed to load, when `isSupported()` is `false`.
 * `undefined` when the addon loaded, or when it was disabled deliberately via
 * `SEEKITE_DISABLE_NATIVE`. Useful in diagnostics; not something callers throw.
 */
export function nativeBindingError(): Error | undefined {
  loadBinding();
  return nativeDisabled() ? undefined : bindingError;
}

function requireBinding(): NativeBinding {
  const loaded = loadBinding();
  if (!loaded) {
    throw new Error(
      nativeDisabled()
        ? "@seekite/engine-native is disabled by SEEKITE_DISABLE_NATIVE; use the wasm engine"
        : "@seekite/engine-native has no prebuilt binary for this platform; " +
            "check isSupported() first and fall back to the wasm engine",
      { cause: bindingError },
    );
  }
  return loaded;
}

// ── Engine construction ─────────────────────────────────────────────────────

/**
 * Model weights ship once per package, not once per platform binary: the
 * native addon is built without the engine crate's `embedded_model` feature and
 * is handed these bytes at construction. Regenerate them with
 * `node scripts/extract-model.mjs`.
 */
function modelPath(model: NativeModelName): string {
  return fileURLToPath(new URL(`../models/${model}-int4.bin`, import.meta.url));
}

// Parsing a model costs a full layout walk plus weight pre-decode (~5–7 MB of
// work), so engines are memoised per model name. They are immutable and
// thread-safe once built, so sharing one across all callers is strictly better
// than each caller holding its own copy.
const engines = new Map<NativeModelName, NativeEngine>();

/**
 * Load (or reuse) the native engine for `model`.
 *
 * Throws if no prebuild is available — guard with {@link isSupported}.
 */
export function createNativeEngine(options: NativeEngineOptions = {}): NativeEngine {
  // Availability is checked before the cache so that disabling the addon takes
  // effect even in a process that already built an engine.
  const bindings = requireBinding();
  const model = options.model ?? "mini";
  const cached = engines.get(model);
  if (cached) return cached;

  const native = new bindings.Engine(readFileSync(modelPath(model)));
  const dimensions = native.dimensions();

  const engine: NativeEngine = {
    dimensions,
    embed: (text) => native.embed(text),
    embedBatch: (texts, concurrency) => native.embedBatch(texts, concurrency ?? null),
    configSummary: () => native.configSummary(),
  };
  engines.set(model, engine);
  return engine;
}

// ── Hashing ─────────────────────────────────────────────────────────────────

/**
 * XXH64 of `input`, as an unsigned 64-bit `bigint`.
 *
 * A `bigint` rather than a `number` because the top 11 bits of a 64-bit hash do
 * not survive a double; truncating them would quietly weaken every cache key
 * built on this (spec 06).
 */
export function xxhash64(input: string | Uint8Array, seed?: bigint): bigint {
  const bytes =
    typeof input === "string"
      ? Buffer.from(input, "utf8")
      : Buffer.from(input.buffer, input.byteOffset, input.byteLength);
  return requireBinding().xxhash64(bytes, seed ?? null);
}
